apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: wytzuo450-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/wytzuo450-dotnet-basic-gitops